// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/blog': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog').default>>>>
    }
    '/api/blogs': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blogs').default>>>>
    }
    '/api/doc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/doc').default>>>>
    }
    '/api/docs': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}